// <auto-generated />
using System;
using Core.EntityFrameWork;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace 景区系统.Database.Migrations.Migrations
{
    [DbContext(typeof(MasterDbContext_SQL))]
    [Migration("20240709035850_v1.0.2")]
    partial class v102
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("景区系统.Core.Entity.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Icon")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("菜单图标");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("软删除");

                    b.Property<string>("MenuName")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasComment("菜单名称");

                    b.Property<string>("MenuUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("菜单跳转链接");

                    b.Property<int>("ParentID")
                        .HasColumnType("int")
                        .HasComment("父级菜单ID");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序顺序");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });
#pragma warning restore 612, 618
        }
    }
}
